{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "wikijs.pgName" . }}
  labels:
    {{- include "wikijs.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.postgres.instances }}
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: {{ .Values.wiki.externalPostgresql.database }}
      owner: {{ .Values.wiki.externalPostgresql.username }}
      encoding: UTF8

  storage:
    size: {{ .Values.postgres.storage.size }}
    {{- with .Values.postgres.storage.storageClass }}
    storageClass: {{ . }}
    {{- end }}

  resources:
    {{- toYaml .Values.postgres.resources | nindent 4 }}

  affinity:
    podAntiAffinityType: preferred
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
